main/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('', index),
    path('about/', about),
    path('contact/', contact),
]

sandika_personal/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('schedule/', include('schedule.urls')),
    path('', include('main.urls'))
]

schedule/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *

urlpatterns = [
    path('', schedule),
    path('submitted-form/', submit_form),
    path('clear-data/', clear_data)
]

main/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models
import django

# Create your models here.
class PersonalSchedule(models.Model):
	def __str__(self):
		return ('Activity: ' + self.activity_name)

	activity_name = models.CharField(max_length=30)
	date = models.DateField(default=django.utils.timezone.now)
	time = models.TimeField(default=django.utils.timezone.now)
	location = models.CharField(max_length=30)

	ACADEMIC = 'AC'
	EXTRACURRICULAR = 'EX'
	HOLIDAY = 'HL'
	PERSONAL = 'PS'
	CATEGORY_CHOICES = (
		(ACADEMIC, 'Academic'),
		(EXTRACURRICULAR, 'Extracurricular'),
		(HOLIDAY, 'Holiday'),
		(PERSONAL, 'Personal'),
		)

	category = models.CharField(
		max_length = 2,
		choices = CATEGORY_CHOICES,
		)

schedule/forms.py
from django import forms
from .models import PersonalSchedule

class ScheduleForm(forms.ModelForm):
	class Meta:
		model = PersonalSchedule
		fields = ['activity_name', 'date', 'location', 'category']
	activity_name = forms.CharField(label='Activity Name', max_length=30)
	date = forms.DateField(label="Date", widget=forms.SelectDateWidget(empty_label=("Year", "Month", "Day")))
	time = forms.TimeField(label="Time", widget=forms.TimeInput(format="%H:%M"))
	location = forms.CharField(label='Location', max_length=30)

	ACADEMIC = 'AC'
	EXTRACURRICULAR = 'EX'
	HOLIDAY = 'HL'
	PERSONAL = 'PS'
	CATEGORY_CHOICES = (
		(ACADEMIC, 'Academic'),
		(EXTRACURRICULAR, 'Extracurricular'),
		(HOLIDAY, 'Holiday'),
		(PERSONAL, 'Personal'),
		)	
	category = forms.ChoiceField(
		choices = CATEGORY_CHOICES,
		)

main/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
	return render(request, 'index.html')

def about(request):
	return render(request, 'about.html')

def contact(request):
	return render(request, 'contact.html')

sandika_personal/views.py
from django.shortcuts import render

# Create your views here.

schedule/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from  .models import PersonalSchedule

from .forms import ScheduleForm

# Create your views here.

def schedule(request):
	form = ScheduleForm()
	my_data = PersonalSchedule.objects.all()

	return render(request, 'schedule.html', {'form' : form, 'my_data' : my_data})


def submit_form(request):
	if request.method == 'POST':
		form = ScheduleForm(request.POST)
		if form.is_valid():
			new_form = form.save()
			return HttpResponseRedirect('/schedule/')

	return render(request, 'schedule.html', {'form' : form})

def clear_data(request):
	PersonalSchedule.objects.all().delete()

	return HttpResponseRedirect('/schedule/')

main/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About - Sandika{% endblock %}
{% block bg-img %}{% static 'background-images/AboutLine.png' %}{% endblock %}
{% block bg-img-width %}screen-width{% endblock %}

{% block body %}
		<div class="row">
			<div class="container">
				<hr style="border: 65px solid transparent;">
			</div>
		</div>

		<div class="row">
			<div class="container col-lg-3 col-md-3 col-sm-3">
				<img src="{% static 'SandikaPortrait.png' %}" width="250vw">
			</div>
			<div class="container col-lg-6 col-md-8 col-sm-6 md-font lg-font">
				<p><b>Name:</b> Sandika P. Putra
				<br/><b>Birthdate:</b> April 16, 1999
				<br/><b>Birthplace:</b> Masbagik, Nusa Tenggara Barat
				<br/><b>Education:</b> Currently pursuing a major in information system
				<br/><b>Institution:</b> Universitas Indonesia
			</p>
			</div>
		</div>

		<div class="row">
			<div class="container">
				<hr style="border: 230px solid transparent;">
			</div>
		</div>

		<div class="row">
			<div class="container d-lg-block d-none">
				<hr style="border: 50px solid transparent;">
			</div>
		</div>

		<div class="container col-lg-12 col-md-12 col-sm-12">
			<p style="text-align: center; font-weight: bold; font-size: 50px;">§ Experiences §</p>
			<p style="text-align: center; font-size: 30px;">
				➣ Experience 1, in what field, performing what task, etc.<br/><br/>

				➣ Experience 2, in what field, performing what task, etc.<br/><br/>

				➣ Experience 3, in what field, performing what task, etc.<br/><br/>

				➣ Experience 4, in what field, performing what task, etc.
			</p>
		</div>

		<div class="container">
			<hr style="border: 100px solid transparent;">
		</div>
{% endblock %}

main/templates/base.html
<!DOCTYPE>
{% load static %}

<html>
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
		<link rel="stylesheet" href="{% static 'defaultstylesheet.css' %}" type="text/css">
		<title>{% block title %}Home - Sandika{% endblock %}</title>
	</head>

	<body class="{% block bodyclass %}{% endblock %} bgcolor" {% block bodystyle %}style="background-image:url({% block bg-img %}{% static 'background-images/HomepageLine.png' %}{% endblock %}); background-size: {% block bg-img-width %}cover{% endblock %};"{% endblock %}>
		<div class="row">
			<div class="container col-md-12 col-sm-12">
				<ul class="nav justify-content-center" style="padding-bottom:0px">
				  <li class="nav-item">
				    <a class="nav-link white" href="../">Home</a>
				  </li>
				  <a class="nav-link">|</a>
				  <li class="nav-item">
				    <a class="nav-link white" href="../about/">About</a>
				  </li>
				  <a class="nav-link">|</a>
				  <li class="nav-item">
				    <a class="nav-link white" href="../contact/">Contact</a>
				  </li>
				  <a class="nav-link">|</a>
				  <li class="nav-item">
				    <a class="nav-link white" href="../schedule/">Schedule</a>
				  </li>
				</ul>
			</div>
		</div>

		<div class="row">
			<div class="container col-lg-12 col-md-12 col-sm-12">
				<hr style="border: 2px solid white" width="600em" />
			</div>
		</div>

		{% block body %}
		{% endblock %}


	</body>
</html>

main/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Contact - Sandika{% endblock %}
{% block bodystyle %}{% endblock %}
{% block bg-img %}{% static 'background-images/ContactLine.png' %}{% endblock %}
{% block bodyclass %}contact-bg-img{% endblock %}

{% block body %}
		<div class="row">
			<div class="container">
				<hr style="border: 60px solid transparent;">
			</div>
		</div>

		<div class="row">
			<div class="container d-lg-none d-md-block">
				<hr style="border: 60px solid transparent;">
			</div>
		</div>

		<div class="row">
			<div class="container col-sm-12 col-lg-5 contact-align">
				<img src="{% static 'Logo/gmail.png' %}" width="60px">
				<p class="contact-style">sandika.prangga@gmail.com</p>
			</div>
		</div>

		<div class="container">
			<hr style="border: 0.1px solid transparent;">
		</div>

		<div class="row">
			<div class="container col-sm-12 col-lg-5 contact-align">
				<img src="{% static 'Logo/linkedin.png' %}" width="60px">
				<p class="contact-style">/sandika-prangga-putra-6b4398154/</p>
			</div>
		</div>

		<div class="container">
			<hr style="border: 0.1px solid transparent;">
		</div>

		<div class="row">
			<div class="container col-sm-12 col-lg-5 contact-align">
				<img src="{% static 'Logo/facebook.png' %}" width="60px">
				<p class="contact-style">/sandikaSC/</p>
			</div>
		</div>

		<div class="container">
			<hr style="border: 0.1px solid transparent;">
		</div>
		<div class="row">
			<div class="container col-sm-12 col-lg-5 contact-align">
				<img src="{% static 'Logo/instagram.png' %}" width="60px">
				<p class="contact-style">@xandavior</p>
			</div>
		</div>
	{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home - Sandika{% endblock %}
{% block bg-img %}{% static 'background-images/HomepageLine.png' %}{% endblock %}

{% block body %}
		<div class="row">
			<div class="container d-block d-lg-none">
				<hr style="border: 80px solid transparent"/>
			</div>
		</div>

		<div class="row">
			<div class="container col-lg-1 col-md-4 col-sm-4">
				<img src="{% static '/Sandika.png' %}" height="525vh">
			</div>
			<div class="container col-lg-8 col-md-9 col-sm-6 lg-font md-font">
				<p id="introquote"> "Hello, I'm <b>Sandika</b>. <br/>A <b>passionate</b>, full of <br/><b>energy</b> sophomore <br/>currently pursuing major <br/>in information systems. <br/>I have an interest in <br/><b>business</b> especially <br/><b>technology-related <br/>startups</b>." </p>
			</div>		
		</div>

		<div class="row">
			<div class="container d-block d-lg-none">
				<hr style="border: 100px solid transparent"/>
			</div>
		</div>
	{% endblock %}

schedule/templates/schedule.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block title %}Schedule - Sandika{% endblock %}
{% block bg-img %}{% static 'background-images/GuestbookLine.png' %}{% endblock %}
{% block bg-img-width %}cover{% endblock %}

{% block body %}
		<div class="container">
			<hr style="border: 10px solid transparent" width="45%" />
		</div>

		<div class="container" style="width: 600px;">
			<form action="/schedule/submitted-form/" method="post">
				{% csrf_token %}
				{% for row in form %}
					<div class="form-group">
						{{ row.label }}
						{% render_field row class="form-control" %}
					</div>
				{% endfor %}
				<div class="container text-center">
					<button type="submit" class="btn btn-primary">Submit</button>
				</div>
			</form>
			<form action="/schedule/clear-data/">
				<div class="container text-center">
					<button type="submit" class="btn btn-primary">Clear Data</button>
				</div>
			</form>
		</div>

		<div class="container">
			<table class="table table-sm">
				<thead class="thead-dark">
					<tr>
						<th>Activity Name</th>
						<th>Date</th>
						<th>Time</th>
						<th>Location</th>
						<th>Category</th>
					</tr>
				</thead>
				<tbody class="table-info">
					{% for schedule in my_data %}
					<tr>
						<td>{{ schedule.activity_name }}</td>
						<td>{{ schedule.date }}</td>
						<td>{{ schedule.time }}</td>
						<td>{{ schedule.location }}</td>
						<td>{{ schedule.get_category_display }}</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

{% endblock %}